set_property SRC_FILE_INFO {cfile:/users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/constraints/enclustra_ax3_pm3.tcl rfile:../../../../constraints/enclustra_ax3_pm3.tcl id:1 unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/constraints/I2C_constr.xdc rfile:../../../../constraints/I2C_constr.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN P17 [get_ports sysclk]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN M16 [get_ports {leds[0]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN M17 [get_ports {leds[1]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN L18 [get_ports {leds[2]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN M18 [get_ports {leds[3]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports {rgmii_txd[0]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN T18 [get_ports {rgmii_txd[1]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN U17 [get_ports {rgmii_txd[2]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports {rgmii_txd[3]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN T16 [get_ports {rgmii_tx_ctl}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN N16 [get_ports {rgmii_txc}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {rgmii_rxd[0]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {rgmii_rxd[1]}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN V15 [get_ports {rgmii_rxd[2]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {rgmii_rxd[3]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN R16 [get_ports {rgmii_rx_ctl}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN T14 [get_ports {rgmii_rxc}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN M13 [get_ports {phy_rstn}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN K2 [get_ports {cfg[0]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN K1 [get_ports {cfg[1]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN J4 [get_ports {cfg[2]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN H4 [get_ports {cfg[3]}]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C2 [get_ports i2c_reset]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N17 [get_ports i2c_scl]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P18 [get_ports i2c_sda]
