# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/mac_fifo_axi4/mac_fifo_axi4.xci
# IP: The module: 'mac_fifo_axi4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/mac_fifo_axi4/mac_fifo_axi4.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_fifo_axi4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/mac_fifo_axi4/mac_fifo_axi4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_fifo_axi4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/mac_fifo_axi4/mac_fifo_axi4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_fifo_axi4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/mac_fifo_axi4/mac_fifo_axi4.xci
# IP: The module: 'mac_fifo_axi4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/mac_fifo_axi4/mac_fifo_axi4.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_fifo_axi4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/mac_fifo_axi4/mac_fifo_axi4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_fifo_axi4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/mac_fifo_axi4/mac_fifo_axi4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_fifo_axi4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
