# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.cache/wt [current_project]
set_property parent.project_path /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/temac_gbe_v9_0_rgmii/temac_gbe_v9_0_rgmii.xci
set_property used_in_implementation false [get_files -all /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/temac_gbe_v9_0_rgmii/synth/temac_gbe_v9_0_rgmii_board.xdc]
set_property used_in_implementation false [get_files -all /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/temac_gbe_v9_0_rgmii/synth/temac_gbe_v9_0_rgmii.xdc]
set_property used_in_implementation false [get_files -all /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/temac_gbe_v9_0_rgmii/synth/temac_gbe_v9_0_rgmii_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/temac_gbe_v9_0_rgmii/synth/temac_gbe_v9_0_rgmii_clocks.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.runs/temac_gbe_v9_0_rgmii_synth_1 -new_name temac_gbe_v9_0_rgmii -ip [get_ips temac_gbe_v9_0_rgmii]]

if { $cached_ip eq {} } {

synth_design -top temac_gbe_v9_0_rgmii -part xc7a35tcsg324-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix temac_gbe_v9_0_rgmii_ temac_gbe_v9_0_rgmii.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ temac_gbe_v9_0_rgmii_stub.v
 lappend ipCachedFiles temac_gbe_v9_0_rgmii_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ temac_gbe_v9_0_rgmii_stub.vhdl
 lappend ipCachedFiles temac_gbe_v9_0_rgmii_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ temac_gbe_v9_0_rgmii_sim_netlist.v
 lappend ipCachedFiles temac_gbe_v9_0_rgmii_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ temac_gbe_v9_0_rgmii_sim_netlist.vhdl
 lappend ipCachedFiles temac_gbe_v9_0_rgmii_sim_netlist.vhdl

 config_ip_cache -add -dcp temac_gbe_v9_0_rgmii.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips temac_gbe_v9_0_rgmii]
}

rename_ref -prefix_all temac_gbe_v9_0_rgmii_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef temac_gbe_v9_0_rgmii.dcp
create_report "temac_gbe_v9_0_rgmii_synth_1_synth_report_utilization_0" "report_utilization -file temac_gbe_v9_0_rgmii_utilization_synth.rpt -pb temac_gbe_v9_0_rgmii_utilization_synth.pb"

if { [catch {
  write_verilog -force -mode synth_stub /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.runs/temac_gbe_v9_0_rgmii_synth_1/temac_gbe_v9_0_rgmii_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.runs/temac_gbe_v9_0_rgmii_synth_1/temac_gbe_v9_0_rgmii_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.runs/temac_gbe_v9_0_rgmii_synth_1/temac_gbe_v9_0_rgmii_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.runs/temac_gbe_v9_0_rgmii_synth_1/temac_gbe_v9_0_rgmii_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


}; # end if cached_ip 

add_files /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.runs/temac_gbe_v9_0_rgmii_synth_1/temac_gbe_v9_0_rgmii_stub.v -of_objects [get_files /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/temac_gbe_v9_0_rgmii/temac_gbe_v9_0_rgmii.xci]

add_files /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.runs/temac_gbe_v9_0_rgmii_synth_1/temac_gbe_v9_0_rgmii_stub.vhdl -of_objects [get_files /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/temac_gbe_v9_0_rgmii/temac_gbe_v9_0_rgmii.xci]

add_files /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.runs/temac_gbe_v9_0_rgmii_synth_1/temac_gbe_v9_0_rgmii_sim_netlist.v -of_objects [get_files /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/temac_gbe_v9_0_rgmii/temac_gbe_v9_0_rgmii.xci]

add_files /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.runs/temac_gbe_v9_0_rgmii_synth_1/temac_gbe_v9_0_rgmii_sim_netlist.vhdl -of_objects [get_files /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/temac_gbe_v9_0_rgmii/temac_gbe_v9_0_rgmii.xci]

add_files /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.runs/temac_gbe_v9_0_rgmii_synth_1/temac_gbe_v9_0_rgmii.dcp -of_objects [get_files /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/temac_gbe_v9_0_rgmii/temac_gbe_v9_0_rgmii.xci]

if {[file isdir /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.ip_user_files/ip/temac_gbe_v9_0_rgmii]} {
  catch { 
    file copy -force /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.runs/temac_gbe_v9_0_rgmii_synth_1/temac_gbe_v9_0_rgmii_sim_netlist.v /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.ip_user_files/ip/temac_gbe_v9_0_rgmii
  }
}

if {[file isdir /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.ip_user_files/ip/temac_gbe_v9_0_rgmii]} {
  catch { 
    file copy -force /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.runs/temac_gbe_v9_0_rgmii_synth_1/temac_gbe_v9_0_rgmii_sim_netlist.vhdl /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.ip_user_files/ip/temac_gbe_v9_0_rgmii
  }
}

if {[file isdir /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.ip_user_files/ip/temac_gbe_v9_0_rgmii]} {
  catch { 
    file copy -force /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.runs/temac_gbe_v9_0_rgmii_synth_1/temac_gbe_v9_0_rgmii_stub.v /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.ip_user_files/ip/temac_gbe_v9_0_rgmii
  }
}

if {[file isdir /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.ip_user_files/ip/temac_gbe_v9_0_rgmii]} {
  catch { 
    file copy -force /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.runs/temac_gbe_v9_0_rgmii_synth_1/temac_gbe_v9_0_rgmii_stub.vhdl /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.ip_user_files/ip/temac_gbe_v9_0_rgmii
  }
}
