# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.cache/wt [current_project]
set_property parent.project_path /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/ipbus-firmware/components/ipbus_util/firmware/hdl/clocks_7s_extphy_se.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/ipbus-firmware/components/ipbus_eth/firmware/hdl/eth_7s_rgmii.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/components/ipbus_core/firmware/hdl/ipbus_ctrl.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/components/ipbus_util/firmware/hdl/led_stretcher.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/components/ipbus_util/firmware/hdl/ipbus_clock_div.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/transactor.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/transactor_if.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/transactor_sm.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/transactor_cfg.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_if_flat.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_build_ping.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_dualportram_rx.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_build_resend.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_do_rx_reset.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_buffer_selector.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_dualportram_tx.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_rxtransactor_if_simple.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_build_arp.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_build_payload.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_rxram_mux.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_dualportram.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_byte_sum.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_tx_mux.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_txtransactor_if_simple.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_packet_parser.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_clock_crossing_if.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_build_status.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_rxram_shim.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_ipaddr_block.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_rarp_block.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/udp_status_buffer.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/ipbus_package.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/emac_hostbus_decl.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/ipbus_trans_decl.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/trans_arb.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/ipbus_ctrlreg_v.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/hdl/ipbus_decode_fanout.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/ipbus_reg_types.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/imports/hdl/enclustra_ax3_pm3_infra.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/hdl/top_SFPFanout_enclustra.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/hdl/ipbus_example.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_ram.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_ctrlreg_v.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_peephole_ram.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_fabric_sel.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_reg_v.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_util/firmware/hdl/ipbus_decode_ipbus_example.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/hdl/ipbus_fanout_slaves.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/hdl/i2c/i2c_master_bit_ctrl.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/hdl/i2c/i2c_master_byte_ctrl.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/hdl/i2c/i2c_master_top.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/hdl/i2c/i2c_master_registers.vhd
  /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/hdl/i2c/i2c_master_rtl.vhd
}
read_ip -quiet /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/mac_fifo_axi4/mac_fifo_axi4.xci
set_property used_in_implementation false [get_files -all /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/mac_fifo_axi4/mac_fifo_axi4.xdc]
set_property used_in_implementation false [get_files -all /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/mac_fifo_axi4/mac_fifo_axi4_clocks.xdc]
set_property used_in_implementation false [get_files -all /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/mac_fifo_axi4/mac_fifo_axi4_ooc.xdc]

read_ip -quiet /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/temac_gbe_v9_0_rgmii/temac_gbe_v9_0_rgmii.xci
set_property used_in_implementation false [get_files -all /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/temac_gbe_v9_0_rgmii/synth/temac_gbe_v9_0_rgmii_board.xdc]
set_property used_in_implementation false [get_files -all /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/temac_gbe_v9_0_rgmii/synth/temac_gbe_v9_0_rgmii.xdc]
set_property used_in_implementation false [get_files -all /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/temac_gbe_v9_0_rgmii/synth/temac_gbe_v9_0_rgmii_ooc.xdc]
set_property used_in_implementation false [get_files -all /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/work/SFPFanout.srcs/sources_1/ip/temac_gbe_v9_0_rgmii/synth/temac_gbe_v9_0_rgmii_clocks.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc -unmanaged /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/constraints/enclustra_ax3_pm3.tcl
set_property used_in_implementation false [get_files /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/constraints/enclustra_ax3_pm3.tcl]

read_xdc /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/constraints/I2C_constr.xdc
set_property used_in_implementation false [get_files /users/phpgb/workspace/myFirmware/DUNE/SFP_Fanout_pc059/constraints/I2C_constr.xdc]


synth_design -top top -part xc7a35tcsg324-1 -flatten_hierarchy none


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
